# Generated by Django 6.0.4 on 2026-04-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="concerto",
            name="hora",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
