# Generated by Django 6.0.4 on 2026-04-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0002_concerto_hora"),
    ]

    operations = [
        migrations.CreateModel(
            name="Palco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="concerto",
            name="banda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concertos",
                to="festival.banda",
            ),
        ),
        migrations.AlterField(
            model_name="concerto",
            name="dia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concertos",
                to="festival.dia",
            ),
        ),
        migrations.AlterField(
            model_name="concerto",
            name="palco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concertos",
                to="festival.palco",
            ),
        ),
    ]
