# Generated by Django 5.2.13 on 2026-04-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0005_palco_imagem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="concerto",
            unique_together={("dia", "palco", "hora")},
        ),
    ]
