# Generated by Django 5.2.13 on 2026-04-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0006_alter_concerto_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concerto",
            options={"ordering": ["dia__data", "hora"]},
        ),
        migrations.AddField(
            model_name="dia",
            name="cor",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
