# Generated by Django 5.2.13 on 2026-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0007_alter_concerto_options_dia_cor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dia",
            name="cor",
            field=models.CharField(default="#000000", max_length=20),
        ),
    ]
