# Generated by Django 5.2.13 on 2026-04-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0009_palco_acessibilidade_mobilidade_reduzida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="palco",
            name="acessibilidade_mobilidade_reduzida",
        ),
    ]
