# Generated by Django 5.2.13 on 2026-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0010_remove_palco_acessibilidade_mobilidade_reduzida"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dia",
            options={"ordering": ["data"]},
        ),
        migrations.AddField(
            model_name="palco",
            name="acessibilidade_mobilidade_reduzida",
            field=models.BooleanField(default=False),
        ),
    ]
